Saving work

diff --git a/examples/GNUmakefile b/examples/GNUmakefile
--- a/examples/GNUmakefile
+++ b/examples/GNUmakefile
@@ -13,11 +13,21 @@ subdirs :=\
  )\
 )
 
+bootstrap_dirs := $(patsubst %/bootstrap,%,$(wildcard */bootstrap))
+
+# We assume that all the example that have a bootstrap
+# will download their copy of quickbuild.make
+quickbuild_copies :=\
+ $(patsubst %,%/quickbuild.make,\
+ $(filter-out $(bootstrap_dirs), $(subdirs)))
+
 builddirs := $(patsubst %,BUILD_%,$(subdirs))
 
 
 bootstrap_dirs := $(strip\
  $(patsubst %/bootstrap,%,$(wildcard */bootstrap)))
+
+quickbuild_downloads := $(patsubst %,%/quickbuild.make,$(bootstrap_dirs))
 
 repoclean_dirs := $(strip\
  $(patsubst %/RepoClean,%,$(wildcard */RepoClean)))
@@ -30,23 +40,31 @@ test_dirs := $(strip\
 
 installed := $(wildcard */installed)
 
-.PHONY: build clean cleaner distclean bootstrap repoclean test
+.PHONY: build clean cleaner distclean repoclean test
 
-$(builddirs): bootstrap
+.DEFAULT_GOAL := test
+
+$(builddirs): $(quickbuild_downloads)
+	set -e
 	$(MAKE) -C $(patsubst BUILD_%,%,$@) BUILD_PREFIX=../$@
+	if [ -x $(patsubst BUILD_%,%,$@)/test ] ; then\
+          cp $(patsubst BUILD_%,%,$@)/test $@ ; fi
 
+$(quickbuild_copies):
+	cp ../quickbuild.make $@
+
+quickbuild_copies: $(quickbuild_copies)
 
 # We must build and install it in the BUILD_ directories before we
 # build and install them in the source directories.
-build: $(builddirs)
+build: $(quickbuild_copies) $(builddirs)
 	set -e
 	for d in $(builddirs) $(subdirs) ; do\
 	    PREFIX=$(PWD)/$$d/installed $(MAKE) -C $$d $@;\
 	    $(MAKE) -C $$d install $@;\
 	    done
 
-
-bootstrap:
+$(quickbuild_downloads):
 	set -e
 	for d in $(bootstrap_dirs) ; do\
 	    if [ -e "$$d/quickbuild.make" ] ; then continue; fi;\
@@ -59,16 +77,23 @@ debug:
 
 
 test: build
-	err= ; fcount=0 ;\
+	err= ; fcount=0 ; tcount=0;
 	for d in $(test_dirs) $(builddirs) ; do\
-	    echo -e "\n    ----- Running test in $$d -----\n";\
-	    if !(cd $$d && ./test) ; then\
-	    err="$${err}\n test in $$d FAILED\n";\
-	    echo -e "\n   test in $$d FAILED\n";\
-	    let fcount=$${fcount}+1; fi;\
-	    done;\
-	if [ -n "$$err" ] ; then echo -e "\n\n  $${fcount} test(s) failed\n$${err}\n"; exit 1; fi;
-	@echo -e "\n\n   All $(words $(test_dirs)) tests Succeeded\n"
+	  cd $$d ;\
+	  if [ -x test ] ; then \
+            let tcount=$${tcount}+1 ;\
+            echo -e "\n    ----- Running test in $$d -----\n";\
+            if ! ./test ; then\
+              let fcount=$${fcount}+1 ;\
+              err="$${err}\n test in $$d FAILED\n";\
+              echo -e "\n   test in $$d FAILED\n";\
+            fi ;\
+          fi ;\
+          cd .. ;\
+          done ;\
+          if [ -n "$$err" ] ; then echo -e "\n\n  $${fcount}/$${tcount} test(s) failed\n$${err}\n"; exit 1; fi;\
+          echo -e "\n\n   All $${tcount}/$${tcount} tests Succeeded\n"
+
 
 clean cleaner distclean:
 	rm -rf $(builddirs)
@@ -76,9 +101,11 @@ ifneq ($(strip $(installed)),)
 	rm -rf $(installed)
 endif
 	for d in $(subdirs) ; do\
-	    $(MAKE) -C $$d cleaner ; done
+          if [ -f $$d/quickbuild.make ] ; then\
+            $(MAKE) -C $$d cleaner ; fi ;\
+          done
 	for d in $(repoclean_dirs) ; do\
           if !(cd $$d && ./RepoClean) ; then exit 1; fi;\
           done
-
+	rm -rf $(quickbuild_copies)
 
